config/routes.rb
Aclindia::Application.routes.draw do
  resources :samples

  resources :customers

  resources :userroles

  resources :sampleconditions

  resources :sampleunits

  resources :sampleplaces

  resources :seals

  resources :packings

  resources :testrequires

  resources :teststandards

  resources :testmethods

  resources :testparameters

  resources :warehouses

  resources :products

  resources :subcategories

  resources :exchanges

  resources :categories

  resources :lablocationals

  resources :labregionals

  resources :labcentrals

  resources :cities  do 
	 get 'load_states',:on => :collection
  end 

  resources :states

  resources :countries

  resources :users

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'home' => :new
    post 'home' => :create
    delete 'logout' => :destroy
  end

   resources :home

   root :to => "home#index"
   match ':controller(/:action(/:id(.:format)))'
	

end

app/models/sample.rb
class Sample < ActiveRecord::Base
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.xml
  def index
    @samples = Sample.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.xml
  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.xml
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.xml
  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to(@sample, :notice => 'Sample was successfully created.') }
        format.xml  { render :xml => @sample, :status => :created, :location => @sample }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.xml
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to(@sample, :notice => 'Sample was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.xml
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to(samples_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Listing samples</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @samples.each do |sample| %>
  <tr>
    <td><%= link_to 'Show', sample %></td>
    <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
    <td><%= link_to 'Destroy', sample, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>