config/routes.rb
Aclindia::Application.routes.draw do
  resources :samples

  resources :customers

  resources :userroles

  resources :sampleconditions

  resources :sampleunits

  resources :sampleplaces

  resources :seals

  resources :packings

  resources :testrequires

  resources :teststandards

  resources :testmethods

  resources :testparameters

  resources :warehouses

  resources :products

  resources :subcategories

  resources :exchanges

  resources :categories

  resources :lablocationals

  resources :labregionals

  resources :labcentrals

  resources :cities  do 
	 get 'load_states',:on => :collection
  end 

  resources :states

  resources :countries

  resources :users

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'home' => :new
    post 'home' => :create
    delete 'logout' => :destroy
  end

   resources :home

   root :to => "home#index"
   match ':controller(/:action(/:id(.:format)))'
	

end

app/models/packing.rb
#------------------------------
#Author: Chaitanya Ram N
#Model: Packing Information
#--------------------------------
class Packing < ActiveRecord::Base

	default_scope :order => 'name'

	#validations
	validates :name, :presence =>true
  	validates_length_of :description, :maximum => 100,
    :too_long => "%{count} characters is the maximum allowed"

	#Method: Indexing
	define_index do
		indexes name
	end
end

app/controllers/packings_controller.rb
#------------------------------
#Author: Chaitanya Ram N
#Controller: Packing
#--------------------------------
class PackingsController < ApplicationController
  # GET /packings
  # GET /packings.xml
  def index
    @packings = Packing.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @packings }
    end
  end

  # GET /packings/1
  # GET /packings/1.xml
  def show
    @packing = Packing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @packing }
    end
  end

  # GET /packings/new
  # GET /packings/new.xml
  def new
    @packing = Packing.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @packing }
    end
  end

  # GET /packings/1/edit
  def edit
    @packing = Packing.find(params[:id])
  end

  # POST /packings
  # POST /packings.xml
  def create
    @packing = Packing.new(params[:packing])

    respond_to do |format|
      if @packing.save
        format.html { redirect_to(@packing, :notice => 'Packing was successfully created.') }
        format.xml  { render :xml => @packing, :status => :created, :location => @packing }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @packing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /packings/1
  # PUT /packings/1.xml
  def update
    @packing = Packing.find(params[:id])

    respond_to do |format|
      if @packing.update_attributes(params[:packing])
        format.html { redirect_to(@packing, :notice => 'Packing was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @packing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /packings/1
  # DELETE /packings/1.xml
  def destroy
    @packing = Packing.find(params[:id])
    @packing.destroy

    respond_to do |format|
      format.html { redirect_to(packings_url) }
      format.xml  { head :ok }
    end
  end

	def search
		@query = params[:query]
		@packings = Packing.search @query
	end
end

app/helpers/packings_helper.rb
module PackingsHelper
end

app/views/packings/_form.html.erb
<div class="home_form">
<%= form_for(@packing) do |f| %>
  <% if @packing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@packing.errors.count, "error") %> prohibited this packing from being saved:</h2>

      <ul>
      <% @packing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter Package Details</legend>
<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
    <tbody>
   	<tr>
  <div>
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name,:class=>'title'%></td>
  </div>
</tr>
<tr>
  <div>
    <td><%= f.label :description %></td>
    <td><%= f.text_field :description,:class=>'title' %></td>
  </div>
</tr>
<tr>
  <div>
	  <td><%= f.label :status %></td>
      <td><%= f.radio_button :status, 'Active', :checked => true %> Active
    <%= f.radio_button :status, 'Inactive' %> Inactive </td>
  </div>
</tr>
<tr>
  <div>
	<td></td>
   <td><%= f.submit "Save"%></td>
  </div>
</tr>
    </tbody>
</table>
</fieldset>
<% end %>
</div>

app/views/packings/edit.html.erb
<h1>Edit Package</h1>

<%= render 'form' %>

<%= link_to 'Show', @packing %> |
<%= link_to 'Back', packings_path %>

app/views/packings/index.html.erb
<h1>Search Packings</h1>
<!--Start of search text box -->
<%= form_tag :action => 'search' %>
	<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
	<tr>
		<td>Search</td>
		<td><%= text_field_tag :query ,@query ||="Enter Packing Name",:class=>'title',
:onfocus=>"javascript: this.value=''",:onblur=>"javascript: if(this.value=='') this.value='Enter Packing Name'" %></td>
		<td><%= submit_tag "Search" %></td>
	</tr>
	</table>
<%= form_tag %>
<!--end of search text box -->
<h1>Listing Packings</h1>
<!-- START_HIGHLIGHT -->
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<!-- END_HIGHLIGHT -->
<table id="newspaper-b">
    <thead>
    	<tr>
        	<th scope="col">Name</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
 
        </tr>
    </thead>
         <tfoot>
    	<tr>
        	<td colspan="4"></td>
        </tr>
    </tfoot>
<% @packings.each do |packing| %>
  <tr>
    <td><%= packing.name %></td>
    <td><%= link_to 'View', packing %></td>
    <td><%= link_to 'Edit', edit_packing_path(packing) %></td>
    <td><%= link_to 'Delete', packing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Packing', new_packing_path, :class=>"more" %>

app/views/packings/new.html.erb
<h1>New Package</h1>

<%= render 'form' %>

<%= link_to 'Back', packings_path %>

app/views/packings/search.html.erb
<h1>Search Results</h1>
<% if @packings.blank? %>
 	<p>Oops!!! No Matches found.</p>
<% else %>
<table id="newspaper-b">
    <thead>
    	<tr>
        	<th scope="col">Name</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
 
        </tr>
    </thead>
         <tfoot>
    	<tr>
        	<td colspan="4"></td>
        </tr>
    </tfoot>
<% @packings.each do |packing| %>
  <tr>
    <td><%= packing.name %></td>
    <td><%= link_to 'View', packing %></td>
    <td><%= link_to 'Edit', edit_packing_path(packing) %></td>
    <td><%= link_to 'Delete', packing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<% end %>
<%= link_to 'Back to Packings', packings_path %>

app/views/packings/show.html.erb
<!-- START_HIGHLIGHT -->
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<!-- END_HIGHLIGHT -->

<h1>Package Details</h1>
<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
    <tbody>
   	<tr>
  <div>
    <td>Name</td>
    <td>  <%= @packing.name %></td>
  </div>
</tr>
<tr>
  <div>
    <td>Description</td>
    <td><%= @packing.description %></td>
  </div>
</tr>
<tr>
  <div>
	  <td>Status</td>
      <td><%=  @packing.status%> 
</td>
  </div>
</tr>
    </tbody>
</table>

<%= link_to 'Edit', edit_packing_path(@packing) %> |
<%= link_to 'Back', packings_path %>