config/routes.rb
Aclindia::Application.routes.draw do
  resources :samples

  resources :customers

  resources :userroles

  resources :sampleconditions

  resources :sampleunits

  resources :sampleplaces

  resources :seals

  resources :packings

  resources :testrequires

  resources :teststandards

  resources :testmethods

  resources :testparameters

  resources :warehouses

  resources :products

  resources :subcategories

  resources :exchanges

  resources :categories

  resources :lablocationals

  resources :labregionals

  resources :labcentrals

  resources :cities  do 
	 get 'load_states',:on => :collection
  end 

  resources :states

  resources :countries

  resources :users

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'home' => :new
    post 'home' => :create
    delete 'logout' => :destroy
  end

   resources :home

   root :to => "home#index"
   match ':controller(/:action(/:id(.:format)))'
	

end

app/models/testparameter.rb
#------------------------------
#Author: Chaitanya Ram N
#Model: Test Parameter Information
#--------------------------------
class Testparameter < ActiveRecord::Base

	default_scope :order => 'name'

	#validations
	validates :name, :presence =>true
	validates_uniqueness_of :name
  	validates_length_of :description, :maximum => 100,
    :too_long => "%{count} characters is the maximum allowed"

	#Method: Indexing
	define_index do
		indexes name
	end
end

app/controllers/testparameters_controller.rb
#------------------------------
#Author: Chaitanya Ram N
#Controller: Test Parameters
#--------------------------------
class TestparametersController < ApplicationController
  # GET /testparameters
  # GET /testparameters.xml
  def index
    @testparameters = Testparameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @testparameters }
    end
  end

  # GET /testparameters/1
  # GET /testparameters/1.xml
  def show
    @testparameter = Testparameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @testparameter }
    end
  end

  # GET /testparameters/new
  # GET /testparameters/new.xml
  def new
    @testparameter = Testparameter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @testparameter }
    end
  end

  # GET /testparameters/1/edit
  def edit
    @testparameter = Testparameter.find(params[:id])
  end

  # POST /testparameters
  # POST /testparameters.xml
  def create
    @testparameter = Testparameter.new(params[:testparameter])

    respond_to do |format|
      if @testparameter.save
        format.html { redirect_to(@testparameter, :notice => 'Test Parameter was successfully created.') }
        format.xml  { render :xml => @testparameter, :status => :created, :location => @testparameter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @testparameter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /testparameters/1
  # PUT /testparameters/1.xml
  def update
    @testparameter = Testparameter.find(params[:id])

    respond_to do |format|
      if @testparameter.update_attributes(params[:testparameter])
        format.html { redirect_to(@testparameter, :notice => 'Test Parameter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @testparameter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /testparameters/1
  # DELETE /testparameters/1.xml
  def destroy
    @testparameter = Testparameter.find(params[:id])
    @testparameter.destroy

    respond_to do |format|
      format.html { redirect_to(testparameters_url) }
      format.xml  { head :ok }
    end
  end

	#search
	def search
		@query = params[:query]
		@testparameters = Testparameter.search @query
	end
end

app/helpers/testparameters_helper.rb
module TestparametersHelper
end

app/views/testparameters/_form.html.erb
<div class="home_form">
<%= form_for(@testparameter) do |f| %>
  <% if @testparameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testparameter.errors.count, "error") %> prohibited this testparameter from being saved:</h2>

      <ul>
      <% @testparameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <legend>Enter Test Method Details</legend>
<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
    <tbody>
   	<tr>
  <div>
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name,:class=>'title'%></td>
  </div>
</tr>
<tr>
  <div>
    <td><%= f.label :description %></td>
    <td><%= f.text_field :description,:class=>'title' %></td>
  </div>
</tr>
<tr>
  <div>
	  <td><%= f.label :status %></td>
      <td><%= f.radio_button :status, 'Active', :checked => true %> Active
    <%= f.radio_button :status, 'Inactive' %> Inactive </td>
  </div>
</tr>
<tr>
  <div>
	<td></td>
   <td><%= f.submit "Save"%></td>
  </div>
</tr>
    </tbody>
</table>
</fieldset>
<% end %>
</div>

app/views/testparameters/edit.html.erb
<h1>Editing Test Parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @testparameter %> |
<%= link_to 'Back', testparameters_path %>

app/views/testparameters/index.html.erb
<h1>Search Test Parameters</h1>
<!--Start of search text box -->
<%= form_tag :action => 'search' %>
	<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
	<tr>
		<td>Search</td>
		<td><%= text_field_tag :query ,@query ||="Enter Test Parameter Name",:class=>'title',
:onfocus=>"javascript: this.value=''",:onblur=>"javascript: if(this.value=='') this.value='Enter Test Parameter Name'" %></td>
		<td><%= submit_tag "Search" %></td>
	</tr>
	</table>
<%= form_tag %>
<!--end of search text box -->
<h1>Listing Test Parameters</h1>
<!-- START_HIGHLIGHT -->
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<!-- END_HIGHLIGHT -->
<table id="newspaper-b">
    <thead>
    	<tr>
        	<th scope="col">Sample Parameter</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
 
        </tr>
    </thead>
         <tfoot>
    	<tr>
        	<td colspan="4"></td>
        </tr>
    </tfoot>
<% @testparameters.each do |testparameter| %>
  <tr>
    <td><%= testparameter.name %></td>
    <td><%= link_to 'View', testparameter %></td>
    <td><%= link_to 'Edit', edit_testparameter_path(testparameter) %></td>
    <td><%= link_to 'Delete', testparameter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Test Parameter', new_testparameter_path, :class=>"more" %>

app/views/testparameters/new.html.erb
<h1>New Test Parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', testparameters_path %>

app/views/testparameters/search.html.erb
<h1>Search Results</h1>
<% if @testparameters.blank? %>
 	<p>Oops!!! No Matches found.</p>
<% else %>
<table id="newspaper-b">
    <thead>
    	<tr>
        	<th scope="col">Sample Parameter</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
 
        </tr>
    </thead>
         <tfoot>
    	<tr>
        	<td colspan="4"></td>
        </tr>
    </tfoot>
<% @testparameters.each do |testparameter| %>
  <tr>
    <td><%= testparameter.name %></td>
    <td><%= link_to 'View', testparameter %></td>
    <td><%= link_to 'Edit', edit_testparameter_path(testparameter) %></td>
    <td><%= link_to 'Delete', testparameter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<% end %>
<%= link_to 'Back to Parameters', testparameters_path %>

app/views/testparameters/show.html.erb
<!-- START_HIGHLIGHT -->
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<!-- END_HIGHLIGHT -->

<h1>Test Parameter Details</h1>
<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
    <tbody>
   	<tr>
  <div>
    <td>Name</td>
    <td>  <%= @testparameter.name %></td>
  </div>
</tr>
<tr>
  <div>
    <td>Description</td>
    <td><%= @testparameter.description %></td>
  </div>
</tr>
<tr>
  <div>
	  <td>Status</td>
      <td><%= @testparameter.status %></td>
  </div>
</tr>
    </tbody>
</table>


<%= link_to 'Edit', edit_testparameter_path(@testparameter) %> |
<%= link_to 'Back', testparameters_path %>