config/routes.rb
Aclindia::Application.routes.draw do
  resources :samples

  resources :customers

  resources :userroles

  resources :sampleconditions

  resources :sampleunits

  resources :sampleplaces

  resources :seals

  resources :packings

  resources :testrequires

  resources :teststandards

  resources :testmethods

  resources :testparameters

  resources :warehouses

  resources :products

  resources :subcategories

  resources :exchanges

  resources :categories

  resources :lablocationals

  resources :labregionals

  resources :labcentrals

  resources :cities  do 
	 get 'load_states',:on => :collection
  end 

  resources :states

  resources :countries

  resources :users

  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'home' => :new
    post 'home' => :create
    delete 'logout' => :destroy
  end

   resources :home

   root :to => "home#index"
   match ':controller(/:action(/:id(.:format)))'
	

end

app/models/testmethod.rb
#------------------------------
#Author: Chaitanya Ram N
#Model: Test Method Information
#--------------------------------
class Testmethod < ActiveRecord::Base

	default_scope :order => 'name'

	#validations
	validates :name, :presence =>true
	validates_uniqueness_of :name
  	validates_length_of :description, :maximum => 100,
    :too_long => "%{count} characters is the maximum allowed"

	#Method: Indexing
	define_index do
		indexes name
	end
end

app/controllers/testmethods_controller.rb
#------------------------------
#Author: Chaitanya Ram N
#Controller: Test Methods
#--------------------------------
class TestmethodsController < ApplicationController
  # GET /testmethods
  # GET /testmethods.xml
  def index
    @testmethods = Testmethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @testmethods }
    end
  end

  # GET /testmethods/1
  # GET /testmethods/1.xml
  def show
    @testmethod = Testmethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @testmethod }
    end
  end

  # GET /testmethods/new
  # GET /testmethods/new.xml
  def new
    @testmethod = Testmethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @testmethod }
    end
  end

  # GET /testmethods/1/edit
  def edit
    @testmethod = Testmethod.find(params[:id])
  end

  # POST /testmethods
  # POST /testmethods.xml
  def create
    @testmethod = Testmethod.new(params[:testmethod])

    respond_to do |format|
      if @testmethod.save
        format.html { redirect_to(@testmethod, :notice => 'Test Method was successfully created.') }
        format.xml  { render :xml => @testmethod, :status => :created, :location => @testmethod }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @testmethod.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /testmethods/1
  # PUT /testmethods/1.xml
  def update
    @testmethod = Testmethod.find(params[:id])

    respond_to do |format|
      if @testmethod.update_attributes(params[:testmethod])
        format.html { redirect_to(@testmethod, :notice => 'Test Method was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @testmethod.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /testmethods/1
  # DELETE /testmethods/1.xml
  def destroy
    @testmethod = Testmethod.find(params[:id])
    @testmethod.destroy

    respond_to do |format|
      format.html { redirect_to(testmethods_url) }
      format.xml  { head :ok }
    end
  end

	#search
	def search
		@query = params[:query]
		@testmethods = Testmethod.search @query
	end
end

app/helpers/testmethods_helper.rb
module TestmethodsHelper
end

app/views/testmethods/_form.html.erb
<div class="home_form">
<%= form_for(@testmethod) do |f| %>
  <% if @testmethod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testmethod.errors.count, "error") %> prohibited this testmethod from being saved:</h2>

      <ul>
      <% @testmethod.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <legend>Enter Test Method Details</legend>
<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
    <tbody>
   	<tr>
  <div>
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name,:class=>'title'%></td>
  </div>
</tr>
<tr>
  <div>
    <td><%= f.label :description %></td>
    <td><%= f.text_field :description,:class=>'title' %></td>
  </div>
</tr>
<tr>
  <div>
	  <td><%= f.label :status %></td>
      <td><%= f.radio_button :status, 'Active', :checked => true %> Active
    <%= f.radio_button :status, 'Inactive' %> Inactive </td>
  </div>
</tr>
<tr>
  <div>
	<td></td>
   <td><%= f.submit "Save"%></td>
  </div>
</tr>
    </tbody>
</table>
</fieldset>
<% end %>
</div>

app/views/testmethods/edit.html.erb
<h1>Edit Test Method</h1>

<%= render 'form' %>

<%= link_to 'Show', @testmethod %> |
<%= link_to 'Back', testmethods_path %>

app/views/testmethods/index.html.erb
<h1>Search Test Methods</h1>
<!--Start of search text box -->
<%= form_tag :action => 'search' %>
	<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
	<tr>
		<td>Search</td>
		<td><%= text_field_tag :query ,@query ||="Enter Test Method Name",:class=>'title',
:onfocus=>"javascript: this.value=''",:onblur=>"javascript: if(this.value=='') this.value='Enter Test Method Name'" %></td>
		<td><%= submit_tag "Search" %></td>
	</tr>
	</table>
<%= form_tag %>
<!--end of search text box -->
<h1>Listing Test Methods</h1>
<!-- START_HIGHLIGHT -->
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<!-- END_HIGHLIGHT -->
<table id="newspaper-b">
    <thead>
    	<tr>
        	<th scope="col">Test Method</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
 
        </tr>
    </thead>
         <tfoot>
    	<tr>
        	<td colspan="4"></td>
        </tr>
    </tfoot>
<% @testmethods.each do |testmethod| %>
  <tr>
    <td><%= testmethod.name %></td>
    <td><%= link_to 'View', testmethod %></td>
    <td><%= link_to 'Edit', edit_testmethod_path(testmethod) %></td>
    <td><%= link_to 'Delete', testmethod, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Test Method', new_testmethod_path, :class=>"more" %>

app/views/testmethods/new.html.erb
<h1>New Test Method</h1>

<%= render 'form' %>

<%= link_to 'Back', testmethods_path %>

app/views/testmethods/search.html.erb
<h1>Search Results</h1>
<% if @testmethods.blank? %>
 	<p>Oops!!! No Matches found.</p>
<% else %>
<table id="newspaper-b">
    <thead>
    	<tr>
        	<th scope="col">Test Method</th>
            <th scope="col">View</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
 
        </tr>
    </thead>
         <tfoot>
    	<tr>
        	<td colspan="4"></td>
        </tr>
    </tfoot>
<% @testmethods.each do |testmethod| %>
  <tr>
    <td><%= testmethod.name %></td>
    <td><%= link_to 'View', testmethod %></td>
    <td><%= link_to 'Edit', edit_testmethod_path(testmethod) %></td>
    <td><%= link_to 'Delete', testmethod, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<% end %>
<%= link_to 'Back to Methods', testmethods_path %>

app/views/testmethods/show.html.erb
<!-- START_HIGHLIGHT -->
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<!-- END_HIGHLIGHT -->

<h1>Test Method Details</h1>
<table id="one-column-emphasis">
    <colgroup>
    	<col class="oce-first" />
    </colgroup>
    <tbody>
   	<tr>
  <div>
    <td>Name</td>
    <td>  <%= @testmethod.name %></td>
  </div>
</tr>
<tr>
  <div>
    <td>Description</td>
    <td><%= @testmethod.description %></td>
  </div>
</tr>
<tr>
  <div>
	  <td>Status</td>
      <td><%= @testmethod.status %></td>
  </div>
</tr>
    </tbody>
</table>

<%= link_to 'Edit', edit_testmethod_path(@testmethod) %> |
<%= link_to 'Back', testmethods_path %>